#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

PATH=/usr/local/bin:$PATH

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
# pyenvとanacondaのactivate衝突問題を回避するため、
# pyenvのinitを行わない。
export PATH=$PYENV_ROOT/versions/miniconda3-4.1.11/bin:$PATH
#if [ -d "$PYENV_ROOT" ]; then
#    export PATH=$PYENV_ROOT/bin:$PATH
#    eval "$(pyenv init -)"
#fi

# golang
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin":$PATH


# rbenv
export RBENV_ROOT="$HOME/.rbenv"
if [ -d "$RBENV_ROOT" ]; then
    export PATH=$RBENV_ROOT/bin:$PATH
    eval "$(rbenv init -)"
fi


# nodebrew
export NODEBREW_ROOT="$HOME/.nodebrew"
if [ -d "$NODEBREW_ROOT" ]; then
    export PATH=$NODEBREW_ROOT/current/bin:$PATH
fi


# brew-file
if [ -f $(brew --prefix)/etc/brew-wrap ];then
    source $(brew --prefix)/etc/brew-wrap
fi
